version: "3.9"
services:
  api:
    build:
      context: ./api
    image: backend
    ports:
      - 6969:6969
  front:
    build: 
      context: ./front
    image: frontend
    ports:
      - 3000:3000

    